package main

import "strings"

// ✅ Full country name as key - accurate matching
var flagMap = map[string]string{
	"afghanistan":              "🇦🇫",
	"albania":                  "🇦🇱",
	"algeria":                  "🇩🇿",
	"andorra":                  "🇦🇩",
	"angola":                   "🇦🇴",
	"antigua and barbuda":      "🇦🇬",
	"argentina":                "🇦🇷",
	"armenia":                  "🇦🇲",
	"australia":                "🇦🇺",
	"austria":                  "🇦🇹",
	"azerbaijan":               "🇦🇿",
	"bahamas":                  "🇧🇸",
	"bahrain":                  "🇧🇭",
	"bangladesh":               "🇧🇩",
	"barbados":                 "🇧🇧",
	"belarus":                  "🇧🇾",
	"belgium":                  "🇧🇪",
	"belize":                   "🇧🇿",
	"benin":                    "🇧🇯",
	"bhutan":                   "🇧🇹",
	"bolivia":                  "🇧🇴",
	"bosnia and herzegovina":   "🇧🇦",
	"botswana":                 "🇧🇼",
	"brazil":                   "🇧🇷",
	"brunei":                   "🇧🇳",
	"bulgaria":                 "🇧🇬",
	"burkina faso":             "🇧🇫",
	"burundi":                  "🇧🇮",
	"cambodia":                 "🇰🇭",
	"cameroon":                 "🇨🇲",
	"canada":                   "🇨🇦",
	"cape verde":               "🇨🇻",
	"central african republic": "🇨🇫",
	"chad":                     "🇹🇩",
	"chile":                    "🇨🇱",
	"china":                    "🇨🇳",
	"colombia":                 "🇨🇴",
	"comoros":                  "🇰🇲",
	"congo":                    "🇨🇬",
	"costa rica":               "🇨🇷",
	"croatia":                  "🇭🇷",
	"cuba":                     "🇨🇺",
	"cyprus":                   "🇨🇾",
	"czech republic":           "🇨🇿",
	"denmark":                  "🇩🇰",
	"djibouti":                 "🇩🇯",
	"dominica":                 "🇩🇲",
	"dominican republic":       "🇩🇴",
	"ecuador":                  "🇪🇨",
	"egypt":                    "🇪🇬",
	"el salvador":              "🇸🇻",
	"equatorial guinea":        "🇬🇶",
	"eritrea":                  "🇪🇷",
	"estonia":                  "🇪🇪",
	"eswatini":                 "🇸🇿",
	"ethiopia":                 "🇪🇹",
	"finland":                  "🇫🇮",
	"france":                   "🇫🇷",
	"gabon":                    "🇬🇦",
	"gambia":                   "🇬🇲",
	"georgia":                  "🇬🇪",
	"germany":                  "🇩🇪",
	"ghana":                    "🇬🇭",
	"greece":                   "🇬🇷",
	"grenada":                  "🇬🇩",
	"guatemala":                "🇬🇹",
	"guinea":                   "🇬🇳",
	"guinea-bissau":            "🇬🇼",
	"guyana":                   "🇬🇾",
	"haiti":                    "🇭🇹",
	"honduras":                 "🇭🇳",
	"hungary":                  "🇭🇺",
	"iceland":                  "🇮🇸",
	"india":                    "🇮🇳",
	"indonesia":                "🇮🇩",
	"iran":                     "🇮🇷",
	"iraq":                     "🇮🇶",
	"ireland":                  "🇮🇪",
	"israel":                   "🇮🇱",
	"italy":                    "🇮🇹",
	"ivory coast":              "🇨🇮",
	"jamaica":                  "🇯🇲",
	"japan":                    "🇯🇵",
	"jordan":                   "🇯🇴",
	"kazakhstan":               "🇰🇿",
	"kenya":                    "🇰🇪",
	"kiribati":                 "🇰🇮",
	"kuwait":                   "🇰🇼",
	"kyrgyzstan":               "🇰🇬",
	"kosovo":                   "🇽🇰",
	"laos":                     "🇱🇦",
	"latvia":                   "🇱🇻",
	"lebanon":                  "🇱🇧",
	"lesotho":                  "🇱🇸",
	"liberia":                  "🇱🇷",
	"libya":                    "🇱🇾",
	"liechtenstein":            "🇱🇮",
	"lithuania":                "🇱🇹",
	"luxembourg":               "🇱🇺",
	"madagascar":               "🇲🇬",
	"malawi":                   "🇲🇼",
	"malaysia":                 "🇲🇾",
	"maldives":                 "🇲🇻",
	"mali":                     "🇲🇱",
	"malta":                    "🇲🇹",
	"mexico":                   "🇲🇽",
	"mongolia":                 "🇲🇳",
	"morocco":                  "🇲🇦",
	"mozambique":               "🇲🇿",
	"myanmar":                  "🇲🇲",
	"namibia":                  "🇳🇦",
	"nepal":                    "🇳🇵",
	"netherlands":              "🇳🇱",
	"new zealand":              "🇳🇿",
	"nicaragua":                "🇳🇮",
	"niger":                    "🇳🇪",
	"nigeria":                  "🇳🇬",
	"north korea":              "🇰🇵",
	"norway":                   "🇳🇴",
	"oman":                     "🇴🇲",
	"pakistan":                 "🇵🇰",
	"panama":                   "🇵🇦",
	"papua new guinea":         "🇵🇬",
	"paraguay":                 "🇵🇾",
	"peru":                     "🇵🇪",
	"philippines":              "🇵🇭",
	"poland":                   "🇵🇱",
	"portugal":                 "🇵🇹",
	"palestine":                "🇵🇸",
	"qatar":                    "🇶🇦",
	"romania":                  "🇷🇴",
	"russia":                   "🇷🇺",
	"rwanda":                   "🇷🇼",
	"saudi arabia":             "🇸🇦",
	"senegal":                  "🇸🇳",
	"serbia":                   "🇷🇸",
	"sierra leone":             "🇸🇱",
	"singapore":                "🇸🇬",
	"slovakia":                 "🇸🇰",
	"slovenia":                 "🇸🇮",
	"somalia":                  "🇸🇴",
	"south africa":             "🇿🇦",
	"south korea":              "🇰🇷",
	"spain":                    "🇪🇸",
	"sri lanka":                "🇱🇰",
	"sudan":                    "🇸🇩",
	"sweden":                   "🇸🇪",
	"switzerland":              "🇨🇭",
	"syria":                    "🇸🇾",
	"taiwan":                   "🇹🇼",
	"tajikistan":               "🇹🇯",
	"tanzania":                 "🇹🇿",
	"thailand":                 "🇹🇭",
	"tunisia":                  "🇹🇳",
	"turkey":                   "🇹🇷",
	"turkmenistan":             "🇹🇲",
	"uganda":                   "🇺🇬",
	"ukraine":                  "🇺🇦",
	"united arab emirates":     "🇦🇪",
	"united kingdom":           "🇬🇧",
	"united states":            "🇺🇸",
	"usa":                      "🇺🇸",
	"uk":                       "🇬🇧",
	"uae":                      "🇦🇪",
	"uruguay":                  "🇺🇾",
	"uzbekistan":               "🇺🇿",
	"venezuela":                "🇻🇪",
	"vietnam":                  "🇻🇳",
	"yemen":                    "🇾🇪",
	"zambia":                   "🇿🇲",
	"zimbabwe":                 "🇿🇼",
}

func GetCountryWithFlag(countryName string) (string, string) {
	if countryName == "" {
		return "🌐", "🌐 Unknown"
	}

	clean := strings.ToLower(strings.TrimSpace(countryName))

	// ✅ 1. Full name exact match (most accurate)
	if flag, ok := flagMap[clean]; ok {
		return flag, flag + " " + countryName
	}

	// ✅ 2. Partial match - agar "South Korea" aaye to "south korea" dhundho
	for key, flag := range flagMap {
		if strings.Contains(clean, key) {
			return flag, flag + " " + countryName
		}
	}

	// ✅ 3. First word fallback
	words := strings.Fields(clean)
	if len(words) > 0 {
		if flag, ok := flagMap[words[0]]; ok {
			return flag, flag + " " + countryName
		}
	}

	return "🌐", "🌐 " + countryName
}
